spring:
  application:
    name: order_contract
  kafka:
    bootstrap-servers: kafka-1:9092
    properties:
      schema.registry.url: http://schema-registry:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8089

logging:
  level:
    org:
      springframework:
        kafka: DEBUG
